const KEY='saldo_v01_transactions'; const SETTINGS='saldo_v01_settings';
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let tx=JSON.parse(localStorage.getItem(KEY)||'[]');
let settings=JSON.parse(localStorage.getItem(SETTINGS)||'{"monthlyBudget":0,"goals":[]}'); let view='home';
function save(){localStorage.setItem(KEY,JSON.stringify(tx));localStorage.setItem(SETTINGS,JSON.stringify(settings))}
function currentMonth(){if(!tx.length)return new Date().toISOString().slice(0,7);return tx.map(x=>x.date.slice(0,7)).sort().at(-1)}
function monthData(m=currentMonth()){return tx.filter(x=>x.date.startsWith(m))}
function totals(arr){let income=0,expense=0;arr.forEach(x=>x.amount>=0?income+=x.amount:expense+=-x.amount);return{income,expense,net:income-expense}}
function icon(cat){return ({'Alimentari':'🛒','Ristoranti e bar':'☕','Trasporti':'🚆','Abbonamenti':'▣','Entrate':'↗','Salute':'✚','Commissioni':'€'}[cat]||'•')}
function home(){let a=monthData(),t=totals(a), all=totals(tx), days=31, day=31, remain=Math.max(0,t.net), daily=remain/Math.max(1,days-day+1);let recent=a.slice(0,5);return `<div class=hero><div class=eyebrow>RISULTATO AGOSTO 2026</div><div class="big ${t.net>=0?'positive':'negative'}">${money(t.net)}</div><div class=sub>Entrate meno uscite del mese</div></div><div class=grid><div class=card><span class=eyebrow>ENTRATE</span><b>${money(t.income)}</b></div><div class=card><span class=eyebrow>USCITE</span><b>${money(t.expense)}</b></div><div class=card><span class=eyebrow>MOVIMENTI</span><b>${a.length}</b></div><div class=card><span class=eyebrow>STORICO</span><b>${tx.length}</b></div></div><div class=section-title><h2>Ultimi movimenti</h2><small>agosto</small></div>${recent.map(rowHTML).join('')}<div class=notice>I dati finanziari sono conservati solo sul dispositivo. Il saldo bancario reale verrà configurato separatamente: la somma dei movimenti non viene trattata come saldo del conto.</div>`}
function rowHTML(x){return `<div class=row><div class=badge>${icon(x.category)}</div><div class=grow><strong>${esc(x.description)}</strong><small>${x.date.split('-').reverse().join('/')} · ${esc(x.category)}</small></div><div class="amt ${x.amount>=0?'positive':''}">${money(x.amount)}</div></div>`}
function movements(){let arr=tx.slice(0,150);return `<div class=section-title><h2>Movimenti</h2><small>${tx.length} totali</small></div><div class=filter><button class="chip on">Tutti</button><button class=chip>Entrate</button><button class=chip>Uscite</button></div>${arr.map(rowHTML).join('')}`}
function budget(){let cats={};monthData().filter(x=>x.amount<0).forEach(x=>cats[x.category]=(cats[x.category]||0)-x.amount);let max=Math.max(1,...Object.values(cats));return `<div class=section-title><h2>Budget</h2><small>Agosto 2026</small></div><div class=notice>Questa prima versione mostra quanto hai speso per categoria. Nella prossima fase assegneremo i limiti mensili e calcoleremo il residuo spendibile.</div>${Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class=card style="margin-bottom:9px"><span>${esc(k)}</span><b>${money(v)}</b><div class=bar><i style="width:${v/max*100}%"></i></div></div>`).join('')}`}
function goals(){return `<div class=section-title><h2>Obiettivi</h2></div><div class=empty>◎<br><br>Qui costruiremo fondo di emergenza, risparmi e obiettivi personali.<br>Non imposto cifre senza averle definite con te.</div>`}
function analysis(){let months={};tx.forEach(x=>{let m=x.date.slice(0,7);(months[m]??=[]).push(x)});return `<div class=section-title><h2>Analisi 2026</h2><small>gen–ago</small></div>${Object.keys(months).sort().map(m=>{let t=totals(months[m]);return `<div class=card style="margin-bottom:9px"><span>${new Date(m+'-01T12:00:00').toLocaleDateString('it-IT',{month:'long',year:'numeric'})}</span><b class=${t.net>=0?'positive':'negative'}>${money(t.net)}</b><small class=sub>Entrate ${money(t.income)} · Uscite ${money(t.expense)}</small></div>`}).join('')}`}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('#view').innerHTML=({home,movements,budget,goals,analysis}[view])()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
document.querySelector('#fab').onclick=()=>{let d=document.querySelector('#modal');d.innerHTML=`<form method=dialog id=moveForm><h2>Nuovo movimento</h2><label>Tipo<select id=type><option value="-1">Spesa</option><option value="1">Entrata</option></select></label><label>Importo<input id=amount type=number min=0 step=.01 required inputmode=decimal></label><label>Descrizione<input id=desc required placeholder="Es. Supermercato"></label><label>Categoria<select id=cat>${['Alimentari','Ristoranti e bar','Trasporti','Abbonamenti','Casa','Salute','Svago','Rate e debiti','Altro','Entrate'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Data<input id=date type=date required value="${new Date().toISOString().slice(0,10)}"></label><div class=actions><button class="btn secondary" value=cancel>Annulla</button><button class="btn primary" id=saveMove value=default>Salva</button></div></form>`;d.showModal();d.querySelector('#moveForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;let amount=Number(d.querySelector('#amount').value)*Number(d.querySelector('#type').value);tx.unshift({id:crypto.randomUUID(),date:d.querySelector('#date').value,description:d.querySelector('#desc').value,details:'Inserimento manuale',account:'Manuale',posted:'SI',bankCategory:'',category:d.querySelector('#cat').value,currency:'EUR',amount});tx.sort((a,b)=>b.date.localeCompare(a.date));save();setTimeout(render,0)}};

document.querySelector('#importBtn').onclick=()=>{let input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{let f=input.files?.[0];if(!f)return;try{let data=JSON.parse(await f.text());let imported=Array.isArray(data)?data:data.transactions;if(!Array.isArray(imported))throw new Error('Formato non valido');if(!confirm(`Importare ${imported.length} movimenti? I dati locali attuali verranno sostituiti.`))return;tx=imported;settings=data.settings||settings;tx.sort((a,b)=>b.date.localeCompare(a.date));save();render();alert('Importazione completata.');}catch(e){alert('Impossibile importare il backup: '+e.message)}};input.click()};
document.querySelector('#backupBtn').onclick=()=>{let blob=new Blob([JSON.stringify({version:'0.2',exportedAt:new Date().toISOString(),transactions:tx,settings},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SALDO_backup_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
