const KEY='saldo_v01_transactions', SETTINGS='saldo_v01_settings';
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const monthName=m=>new Date(m+'-01T12:00:00').toLocaleDateString('it-IT',{month:'long',year:'numeric'});
let tx=JSON.parse(localStorage.getItem(KEY)||'[]'), settings=JSON.parse(localStorage.getItem(SETTINGS)||'{}'), view='home', movementFilter='all';
function migrateSettings(){
  const old=settings||{};
  settings={...old};
  settings.fixedIncome=settings.fixedIncome||[{id:'salary',name:'Stipendio',amount:1557,day:14,enabled:true}];
  settings.fixedExpenses=settings.fixedExpenses||[
    {id:'loan',name:'Finanziamento',amount:330.36,day:20,enabled:true},
    {id:'very',name:'Telefonia Very',amount:10,day:1,enabled:true},
    {id:'disney',name:'Disney+',amount:15.99,day:15,enabled:true},
    {id:'netflix',name:'Netflix',amount:24.98,day:27,enabled:true},
    {id:'icloud',name:'Apple',amount:.99,day:25,enabled:true},
    {id:'bank',name:'Canone conto bancario',amount:3,day:30,enabled:true},
    {id:'train',name:'Abbonamento treno',amount:51.30,day:1,enabled:true,startMonth:'2026-10'}
  ];
  // v0.4.1: ChatGPT Plus è una spesa fissa da agosto 2026.
  // Upsert necessario anche per chi ha già salvato fixedExpenses con la v0.4.
  if(!settings.fixedExpenses.some(r=>r.id==='chatgpt')) settings.fixedExpenses.push({id:'chatgpt',name:'ChatGPT Plus',amount:22.99,day:20,enabled:true,startMonth:'2026-08'});
  settings.creditCard={house:500,other:Math.max(0,Number(old.creditCardOutstanding||961.63)-500),debitDay:20,...(old.creditCard||{})};
  settings.budgetLimits={Alimentari:40,Bar:40,Tabacchi:100,Shopping:40,'Salute / cura personale':30,'Extra / svago':100,...(old.budgetLimits||{})};
  settings.goalBalances={university:0,savings:0,aesthetic:0,boat:0,...(old.goalBalances||{})};
  settings.investmentMonthlyTarget=Number(old.investmentMonthlyTarget||100); settings.investedBalance=Number(old.investedBalance||0);
  settings.riskFundBalance=Number(old.riskFundBalance||0);
  delete settings.currentBalance;
}
migrateSettings(); function save(){localStorage.setItem(KEY,JSON.stringify(tx));localStorage.setItem(SETTINGS,JSON.stringify(settings))} save();
function currentMonth(){return new Date().toISOString().slice(0,7)} function monthData(m=currentMonth()){return tx.filter(x=>x.date?.startsWith(m))}
function isCardStatement(x){return /saldo e\/c carta di credito/i.test((x.description||'')+' '+(x.details||''))}
function isRevolut(x){return /revolut/i.test((x.description||'')+' '+(x.details||''))}
function isCashDeposit(x){return x.amount>0&&/versamento contanti/i.test((x.description||'')+' '+(x.details||''))}
function isHouseMooney(x){let s=((x.description||'')+' '+(x.details||'')).toLowerCase();return /mooney/.test(s)&&Math.abs(Number(x.amount))>=400}
function classification(x){if(x.flowType)return x.flowType;if(isCardStatement(x))return'card_statement';if(isRevolut(x))return'wallet_transfer';if(isCashDeposit(x))return'asset_transfer';if(isHouseMooney(x))return'home';return Number(x.amount)>=0?'income':'expense'}
function totals(arr){let income=0,expense=0;arr.forEach(x=>{let c=classification(x);if(c==='income')income+=Number(x.amount);else if(c==='expense')expense+=-Number(x.amount)});return{income,expense,net:income-expense}}
function activeForMonth(r,m=currentMonth()){return r.enabled!==false&&(!r.startMonth||m>=r.startMonth)&&(!r.endMonth||m<=r.endMonth)}
function fixedIncomeTotal(m=currentMonth()){return settings.fixedIncome.filter(r=>activeForMonth(r,m)).reduce((s,r)=>s+Number(r.amount||0),0)}
function fixedExpenseTotal(m=currentMonth()){return settings.fixedExpenses.filter(r=>activeForMonth(r,m)).reduce((s,r)=>s+Number(r.amount||0),0)}
function cardTotal(){return Number(settings.creditCard.house||0)+Number(settings.creditCard.other||0)}
function icon(cat){return ({Alimentari:'🛒',Bar:'☕',Tabacchi:'◉',Shopping:'▱','Salute / cura personale':'✚','Extra / svago':'◈'}[cat]||'•')}
function rowHTML(x){let c=classification(x),tag=(c==='wallet_transfer'||c==='asset_transfer')?' · trasferimento':c==='card_statement'?' · addebito carta':x.paymentMethod==='credit_card'?' · carta di credito':'';return `<div class=row><div class=badge>${icon(x.category)}</div><div class=grow><strong>${esc(x.description)}</strong><small>${x.date.split('-').reverse().join('/')} · ${esc(x.category||'Altro')}${tag}</small></div><div class="amt ${x.amount>=0?'positive':''}">${money(x.amount)}</div></div>`}
function home(){
 const m=currentMonth(), income=fixedIncomeTotal(m), fixed=fixedExpenseTotal(m), card=cardTotal(), residual=income-fixed-card;
 const recent=monthData(m).slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);
 return `<div class=section-title><h2>Entrate fisse</h2><button class=textBtn onclick="openPlanSetup()">Modifica</button></div>
 <div class=planStack>${settings.fixedIncome.filter(r=>activeForMonth(r,m)).map(r=>`<div class=planCard incomeCard><div><small>GIORNO ${r.day}</small><strong>${esc(r.name)}</strong></div><b>${money(r.amount)}</b></div>`).join('')}</div>
 <div class=section-title><h2>Spese fisse</h2><small>${monthName(m)}</small></div>
 <div class=planStack>${settings.fixedExpenses.filter(r=>activeForMonth(r,m)).map(r=>`<div class=planCard><div><small>GIORNO ${r.day}</small><strong>${esc(r.name)}</strong></div><b>− ${money(r.amount)}</b></div>`).join('')}</div>
 <div class=totalStrip><span>Totale spese fisse</span><b>${money(fixed)}</b></div>
 <div class=section-title><h2>Carta di credito</h2><small>addebito giorno ${settings.creditCard.debitDay} mese successivo</small></div>
 <div class=creditSplit><div><small>CASA</small><b>${money(settings.creditCard.house)}</b></div><div><small>ALTRE SPESE</small><b>${money(settings.creditCard.other)}</b></div><div class=creditTotal><span>Totale carta maturato</span><b>${money(card)}</b></div></div>
 <div class="residual ${residual<0?'bad':''}"><div class=eyebrow>RESIDUO REALE</div><div class=big>${money(residual)}</div><p>Entrate fisse ${money(income)} − spese fisse ${money(fixed)} − carta ${money(card)}</p></div>
 <div class=section-title><h2>Ultimi movimenti</h2><button class=textBtn onclick="openMovements()">Tutti i movimenti</button></div>${recent.length?recent.map(rowHTML).join(''):'<div class=emptySmall>Nessun movimento nel mese.</div>'}`
}
window.openMovements=()=>{view='movements';render()};
function movements(){let arr=tx.slice().sort((a,b)=>b.date.localeCompare(a.date));if(movementFilter==='income')arr=arr.filter(x=>Number(x.amount)>0);if(movementFilter==='expense')arr=arr.filter(x=>Number(x.amount)<0);return `<div class=section-title><h2>Movimenti</h2><button class=textBtn onclick="view='home';render()">Torna alla Home</button></div><div class=filter><button class="chip ${movementFilter==='all'?'on':''}" onclick="setMovementFilter('all')">Tutti</button><button class="chip ${movementFilter==='income'?'on':''}" onclick="setMovementFilter('income')">Entrate</button><button class="chip ${movementFilter==='expense'?'on':''}" onclick="setMovementFilter('expense')">Uscite</button></div>${arr.slice(0,200).map(rowHTML).join('')}`}
window.setMovementFilter=f=>{movementFilter=f;render()};
function goalCard(title,target,current,sub,cls=''){let pct=target?Math.min(100,current/target*100):0;return `<div class="goalCard ${cls}"><div class=goalHead><div><small>${esc(sub)}</small><h3>${esc(title)}</h3></div><b>${target?money(target):'Crescita'}</b></div>${target?`<div class=bar><i style="width:${pct}%"></i></div><div class=goalMeta><span>${money(current)} accumulati</span><span>Mancano ${money(Math.max(0,target-current))}</span></div>`:`<div class=growthNumber>${money(current)}</div><div class=goalMeta><span>Capitale che vuoi proteggere e far crescere</span></div>`}</div>`}
function goals(){let cc=cardTotal(),extra=Math.max(0,cc-500),g=settings.goalBalances;return `<div class=section-title><h2>Obiettivi</h2><button class=textBtn onclick="openGoalsSetup()">Aggiorna somme</button></div>
 <div class=goalCard><div class=goalHead><div><small>PRIORITÀ 1</small><h3>Carta di credito</h3></div><b>Target ${money(500)}</b></div><div class=bar><i style="width:${Math.max(0,Math.min(100,500/Math.max(cc,500)*100))}%"></i></div><div class=goalMeta><span>Uso attuale ${money(cc)}</span><span>Extra da eliminare ${money(extra)}</span></div><p class=goalNote>Prima tappa: usare la carta soltanto per i 500 € della casa.</p></div>
 ${goalCard('Università',2500,Number(g.university),'PRIORITÀ 2 · ISCRIZIONE APPENA RAGGIUNTO IL TARGET')}
 ${goalCard('Crescita del conto',0,Number(g.savings),'PRIORITÀ 3 · ANCHE 5 € ALLA VOLTA')}
 ${goalCard('Estetica',4000,Number(g.aesthetic),'OBIETTIVO PERSONALE')}
 ${goalCard('Patente nautica',2000,Number(g.boat),'OBIETTIVO PERSONALE')}`}
function budgetCategory(x){let s=((x.description||'')+' '+(x.details||'')+' '+(x.category||'')).toLowerCase();if(Number(x.amount)>=0||!['expense'].includes(classification(x)))return null;if(/tabacc|tobacco/.test(s))return'Tabacchi';if(/bar |caff|pastic|gelat|ristor|pub|mcdon|burger|deliver|glovo|just eat/.test(s))return'Bar';if(/supermerc|aliment|conad|coop|lidl|eurospin|dok|despar/.test(s))return'Alimentari';if(/farmac|ottic|parruc|barber|salute/.test(s))return'Salute / cura personale';if(/zara|amazon|abbigli|shopping|negozio/.test(s))return'Shopping';return'Extra / svago'}
function budget(){let m=currentMonth(),spent={};Object.keys(settings.budgetLimits).forEach(k=>spent[k]=0);monthData(m).forEach(x=>{let c=budgetCategory(x);if(c)spent[c]=(spent[c]||0)+Math.abs(Number(x.amount))});let totalBudget=Object.values(settings.budgetLimits).reduce((a,b)=>a+Number(b),0),totalSpent=Object.values(spent).reduce((a,b)=>a+b,0),remain=totalBudget-totalSpent;return `<div class=section-title><h2>Budget</h2><small>${monthName(m)}</small></div><div class=budgetSummary><div><small>BUDGET TOTALE</small><b>${money(totalBudget)}</b></div><div><small>SPESO</small><b>${money(totalSpent)}</b></div><div><small>${remain>=0?'RESTA':'SFORATO'}</small><b class="${remain<0?'negative':'positive'}">${money(Math.abs(remain))}</b></div></div>${Object.entries(settings.budgetLimits).map(([k,limit])=>{let v=spent[k]||0,d=Number(limit)-v,pct=Math.min(100,v/Number(limit)*100);return `<div class="budgetCat ${d<0?'over':''}"><div class=catTop><span>${icon(k)} ${esc(k)}</span><b>${money(v)} / ${money(limit)}</b></div><div class=bar><i style="width:${pct}%"></i></div><div class=catMeta>${d>=0?`Ti restano ${money(d)}`:`Sforamento ${money(-d)}`} · ${Math.round(v/Number(limit)*100)}% utilizzato</div></div>`}).join('')}<div class=notice>I 350 € sono un tetto massimo di spesa, non un obiettivo da consumare. Quello che non spendi resta margine libero per far crescere conto, obiettivi e sicurezza.</div>`}
function investments(){let t=Number(settings.investmentMonthlyTarget||100);return `<div class=section-title><h2>Investimenti</h2><button class=textBtn onclick="openInvestmentSetup()">Modifica</button></div><div class=budgetHero><div class=eyebrow>PRIMO TRAGUARDO PAC</div><div class=budgetHeadline>${money(t)}<small>/mese</small></div><div class=sub>È un obiettivo progressivo: prima stabilizziamo il bilancio, poi aumentiamo la quota.</div></div><div class=goalCard><div class=goalHead><div><small>CAPITALE INVESTITO REGISTRATO</small><h3>Piano di accumulo</h3></div><b>${money(settings.investedBalance)}</b></div><p class=goalNote>Non consideriamo il PAC denaro da spendere: quando una quota viene destinata agli investimenti esce dalla disponibilità corrente.</p></div>`}
function risk(){let monthly=fixedExpenseTotal(currentMonth()),target=monthly*6,current=Number(settings.riskFundBalance||0),pct=target?Math.min(100,current/target*100):0,months=monthly?current/monthly:0;return `<div class=section-title><h2>Fondo rischi</h2><button class=textBtn onclick="openRiskSetup()">Aggiorna</button></div><div class=budgetHero><div class=eyebrow>OBIETTIVO SICUREZZA</div><div class=budgetHeadline>${money(target)}</div><div class=sub>6 mesi delle spese fisse attuali (${money(monthly)} al mese)</div></div><div class=goalCard><div class=goalHead><div><small>COPERTURA ATTUALE</small><h3>${months.toFixed(1).replace('.',',')} mesi</h3></div><b>${money(current)}</b></div><div class=bar><i style="width:${pct}%"></i></div><div class=goalMeta><span>${Math.round(pct)}% del target</span><span>Mancano ${money(Math.max(0,target-current))}</span></div></div>`}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('#view').innerHTML=({home,movements,goals,budget,investments,risk}[view]||home)()}
window.openPlanSetup=()=>{let d=document.querySelector('#modal');d.innerHTML=`<form method=dialog id=p><h2>Piano mensile</h2><label>Stipendio previsto<input id=sal type=number step=.01 value="${settings.fixedIncome[0]?.amount||0}"></label><label>Giorno stipendio<input id=sday type=number min=1 max=31 value="${settings.fixedIncome[0]?.day||14}"></label><label>Altre spese carta già maturate<input id=other type=number step=.01 min=0 value="${settings.creditCard.other||0}"></label><div class=help>I 500 € Casa restano separati nella carta. Le spese fisse si modificano nel codice sulla base del piano concordato.</div><div class=actions><button class="btn secondary" value=cancel>Annulla</button><button class="btn primary" value=default>Salva</button></div></form>`;d.showModal();d.querySelector('#p').onsubmit=e=>{if(e.submitter?.value==='cancel')return;settings.fixedIncome[0].amount=Number(d.querySelector('#sal').value||0);settings.fixedIncome[0].day=Number(d.querySelector('#sday').value||14);settings.creditCard.other=Number(d.querySelector('#other').value||0);save();setTimeout(render,0)}};
window.openGoalsSetup=()=>{let g=settings.goalBalances,d=document.querySelector('#modal');d.innerHTML=`<form method=dialog id=g><h2>Somme accantonate</h2><label>Università<input id=u type=number min=0 step=.01 value="${g.university}"></label><label>Crescita conto<input id=s type=number min=0 step=.01 value="${g.savings}"></label><label>Estetica<input id=a type=number min=0 step=.01 value="${g.aesthetic}"></label><label>Patente nautica<input id=b type=number min=0 step=.01 value="${g.boat}"></label><div class=actions><button class="btn secondary" value=cancel>Annulla</button><button class="btn primary" value=default>Salva</button></div></form>`;d.showModal();d.querySelector('#g').onsubmit=e=>{if(e.submitter?.value==='cancel')return;g.university=Number(d.querySelector('#u').value||0);g.savings=Number(d.querySelector('#s').value||0);g.aesthetic=Number(d.querySelector('#a').value||0);g.boat=Number(d.querySelector('#b').value||0);save();setTimeout(render,0)}};
window.openInvestmentSetup=()=>{let v=prompt('Obiettivo mensile PAC (€)',settings.investmentMonthlyTarget);if(v!==null&&!isNaN(Number(v))){settings.investmentMonthlyTarget=Number(v);save();render()}};
window.openRiskSetup=()=>{let v=prompt('Quanto hai già nel fondo rischi? (€)',settings.riskFundBalance);if(v!==null&&!isNaN(Number(v))){settings.riskFundBalance=Number(v);save();render()}};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
document.querySelector('#fab').onclick=()=>{let d=document.querySelector('#modal');d.innerHTML=`<form method=dialog id=moveForm><h2>Nuovo movimento</h2><label>Tipo<select id=type><option value="-1">Spesa</option><option value="1">Entrata</option></select></label><label>Importo<input id=amount type=number min=0 step=.01 required></label><label>Descrizione<input id=desc required></label><label>Categoria<select id=cat>${['Alimentari','Bar','Tabacchi','Shopping','Salute / cura personale','Extra / svago','Abbonamenti','Trasporti','Altro','Entrate'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Pagamento<select id=payment><option value=debit>Conto / bancomat / contanti</option><option value=credit_card>Carta di credito</option></select></label><label>Data<input id=date type=date required value="${new Date().toISOString().slice(0,10)}"></label><div class=actions><button class="btn secondary" value=cancel>Annulla</button><button class="btn primary" value=default>Salva</button></div></form>`;d.showModal();d.querySelector('#moveForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;let sign=Number(d.querySelector('#type').value),amount=Number(d.querySelector('#amount').value)*sign,payment=sign<0?d.querySelector('#payment').value:'income';tx.unshift({id:crypto.randomUUID(),date:d.querySelector('#date').value,description:d.querySelector('#desc').value,details:'Inserimento manuale',account:'Manuale',posted:'SI',bankCategory:'',category:d.querySelector('#cat').value,currency:'EUR',amount,paymentMethod:payment});if(payment==='credit_card')settings.creditCard.other=Number(settings.creditCard.other||0)+Math.abs(amount);save();setTimeout(render,0)}};
document.querySelector('#importBtn').onclick=()=>{let input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{let f=input.files?.[0];if(!f)return;try{let data=JSON.parse(await f.text()),imported=Array.isArray(data)?data:data.transactions;if(!Array.isArray(imported))throw Error('Formato non valido');if(!confirm(`Importare ${imported.length} movimenti?`))return;tx=imported;settings={...settings,...(data.settings||{})};migrateSettings();save();render();alert('Importazione completata.')}catch(e){alert('Importazione non riuscita: '+e.message)}};input.click()};
document.querySelector('#backupBtn').onclick=()=>{let blob=new Blob([JSON.stringify({version:'0.4',exportedAt:new Date().toISOString(),transactions:tx,settings},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SALDO_backup_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').then(r=>r.update()).catch(()=>{});render();
