const KEY='saldo_v01_transactions', SETTINGS='saldo_v01_settings', APP_VERSION='0.6.2';
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n||0)), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const monthNow=()=>new Date().toISOString().slice(0,7), monthName=m=>new Date(m+'-01T12:00:00').toLocaleDateString('it-IT',{month:'long',year:'numeric'}), uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random();
let tx=JSON.parse(localStorage.getItem(KEY)||'[]'), old=JSON.parse(localStorage.getItem(SETTINGS)||'{}'), settings={...old};
settings.fixedIncome=Array.isArray(old.fixedIncome)?old.fixedIncome:[]; settings.fixedExpenses=Array.isArray(old.fixedExpenses)?old.fixedExpenses:[]; settings.budgetLimits=(old.budgetLimits&&typeof old.budgetLimits==='object')?old.budgetLimits:{}; settings.investedBalance=Number(old.investedBalance||0); settings.riskFundBalance=Number(old.riskFundBalance||0); settings.allocations=Array.isArray(old.allocations)?old.allocations:[]; settings.capitalOpening=(old.capitalOpening&&typeof old.capitalOpening==='object')?old.capitalOpening:null; settings.capitalAdjustments=Array.isArray(old.capitalAdjustments)?old.capitalAdjustments:[];
let view='fixed', trendMonth=monthNow(), movementMonth=monthNow(), budgetMonth=monthNow(), movementCat='Tutte';
function save(){localStorage.setItem(KEY,JSON.stringify(tx));localStorage.setItem(SETTINGS,JSON.stringify(settings))}
function active(r,m){if(r.enabled===false)return false;if(r.startMonth&&m<r.startMonth)return false;if(r.endMonth&&m>r.endMonth)return false;return true}
function incomeTotal(m){return settings.fixedIncome.filter(r=>active(r,m)).reduce((s,r)=>s+Number(r.amount||0),0)}
function fixedTotal(m){return settings.fixedExpenses.filter(r=>active(r,m)).reduce((s,r)=>s+Number(r.amount||0),0)}
function categories(){return Object.keys(settings.budgetLimits)}
function textOf(x){return `${x.description||''} ${x.details||''} ${x.category||''} ${x.bankCategory||''}`.toLowerCase()}
function legacyCategory(x){let t=textOf(x),c=String(x.category||'').toLowerCase(),b=String(x.bankCategory||'').toLowerCase();
 if(c.includes('aliment')||b.includes('aliment')||b.includes('supermerc'))return 'Alimentari';
 if(c.includes('ristor')||c==='bar'||b.includes('ristor')||/coffee|bar |caff|maiorano|mimi e coco|justeat|sumup \*a\.s\.d\. profit/.test(t))return 'Bar';
 if(c.includes('tabac')||b.includes('tabac'))return 'Tabacchi';
 if(c.includes('abbigli')||c.includes('shopping')||/zara|abbigli|scarpe|amazon/.test(t))return 'Shopping';
 if(c.includes('salute')||b.includes('vista')||/ottica|farmac|parafarm/.test(t))return 'Salute / cura personale';
 if(c.includes('extra')||c.includes('svago'))return 'Extra / svago'; return null}
function catOf(x){if(x.budgetCategory&&categories().includes(x.budgetCategory))return x.budgetCategory;if(x.category&&categories().includes(x.category))return x.category;let legacy=legacyCategory(x);if(legacy&&categories().includes(legacy))return legacy;let c=String(x.category||x.bankCategory||'').toLowerCase();for(const k of categories())if(c.includes(k.toLowerCase()))return k;return null}
function isTransfer(x){let t=textOf(x),c=String(x.category||'').toLowerCase();return x.flowType==='transfer'||x.flowType==='wallet_transfer'||x.flowType==='asset_transfer'||c.includes('trasferiment')||/bonifico.*salvatore|revolut/.test(t)}
function isCardStatement(x){return x.flowType==='card_statement'||/addebito saldo.*carta|saldo e\/c carta/.test(textOf(x))}
function isFixedActual(x){if(x.flowType==='fixed_expense')return true;let t=textOf(x);return /pag\.finanziamento|finanziamento rateale|disney plus|netflix|canone conto|very mobile/.test(t)||(/apple\.com\/bill/.test(t)&&[.99,22.99].includes(Math.abs(Number(x.amount||0))))}
function isRealVariableExpense(x){return Number(x.amount)<0&&!isTransfer(x)&&!isCardStatement(x)&&!isFixedActual(x)}
function variableTx(m){return tx.filter(x=>String(x.date||'').startsWith(m)&&isRealVariableExpense(x))}
function variableTotal(m){return variableTx(m).reduce((s,x)=>s+Math.abs(Number(x.amount||0)),0)}
function result(m){return incomeTotal(m)-fixedTotal(m)-variableTotal(m)}
function availableMonths(){let set=new Set([monthNow()]);tx.forEach(x=>{if(/^\d{4}-\d{2}/.test(x.date||''))set.add(x.date.slice(0,7))});settings.fixedIncome.forEach(x=>x.startMonth&&set.add(x.startMonth));return [...set].sort()}
function allocFor(dest,m=null){return settings.allocations.filter(a=>a.destination===dest&&(!m||String(a.date||'').startsWith(m))).reduce((s,a)=>s+Number(a.amount||0),0)}
function fixed(){let m=monthNow();return `<div class="section-title"><h2>Entrate fisse</h2><button class="textBtn" onclick="editIncome()">＋ Aggiungi</button></div><div class="planStack">${settings.fixedIncome.filter(r=>active(r,m)).map(r=>`<button class="planCard incomeCard editable" onclick="editIncome('${r.id}')"><div><small>GIORNO ${r.day||1}</small><strong>${esc(r.name)}</strong></div><b>${money(r.amount)}</b></button>`).join('')||'<div class="emptySmall">Nessuna entrata fissa</div>'}</div><div class="totalStrip"><span>Totale entrate fisse</span><b class="positive">${money(incomeTotal(m))}</b></div><div class="section-title"><h2>Spese fisse</h2><button class="textBtn" onclick="editFixed()">＋ Aggiungi</button></div><div class="planStack">${settings.fixedExpenses.filter(r=>active(r,m)).map(r=>`<button class="planCard editable" onclick="editFixed('${r.id}')"><div><small>GIORNO ${r.day||1}</small><strong>${esc(r.name)}</strong></div><b>− ${money(r.amount)}</b></button>`).join('')||'<div class="emptySmall">Nessuna spesa fissa</div>'}</div><div class="totalStrip"><span>Totale spese fisse</span><b>${money(fixedTotal(m))}</b></div>`}
function movements(){let months=availableMonths().slice().reverse(), rows=tx.filter(x=>String(x.date||'').startsWith(movementMonth)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));if(movementCat!=='Tutte')rows=rows.filter(x=>(catOf(x)||'Non classificato')===movementCat);let cats=['Tutte',...categories(),'Non classificato'];return `<div class="section-title"><h2>Movimenti</h2><small>${rows.length} movimenti</small></div><div class="movFilters"><select id="movementMonth">${months.map(m=>`<option value="${m}" ${m===movementMonth?'selected':''}>${monthName(m)}</option>`).join('')}</select><select id="movementCat">${cats.map(c=>`<option ${c===movementCat?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="movementSummary"><span>Uscite reali considerate nel risultato</span><b>${money(variableTotal(movementMonth))}</b></div>${rows.map(x=>{let c=catOf(x)||'Non classificato',a=Number(x.amount||0);return `<div class="row"><div class="badge">${icon(c)}</div><div class="grow"><strong>${esc(x.description||x.details||'Movimento')}</strong><small>${fmtDate(x.date)} · ${esc(c)}${isTransfer(x)?' · trasferimento':isCardStatement(x)?' · addebito carta escluso':isFixedActual(x)?' · già nelle spese fisse':''}</small></div><div class="amt ${a<0?'negative':'positive'}">${a<0?'−':'+'}${money(Math.abs(a))}</div></div>`}).join('')||'<div class="emptySmall">Nessun movimento nel periodo.</div>'}`}
function capitalEligible(x){let posted=String(x.posted||'').toUpperCase(),account=String(x.account||'').toLowerCase();return !posted.startsWith('NO')&&!account.startsWith('carta di credito')}
function capitalFlow(m){let rows=tx.filter(x=>String(x.date||'').startsWith(m)&&capitalEligible(x)),incoming=rows.filter(x=>Number(x.amount)>0).reduce((s,x)=>s+Number(x.amount||0),0),outgoing=rows.filter(x=>Number(x.amount)<0).reduce((s,x)=>s+Math.abs(Number(x.amount||0)),0),adjust=settings.capitalAdjustments.filter(a=>String(a.date||'').startsWith(m)).reduce((s,a)=>s+Number(a.amount||0),0);return {incoming,outgoing,net:incoming-outgoing+adjust,adjust}}
function capitalMonths(){let start=settings.capitalOpening?.date?.slice(0,7),set=new Set();tx.filter(capitalEligible).forEach(x=>/^\d{4}-\d{2}/.test(x.date||'')&&(!start||x.date.slice(0,7)>=start)&&set.add(x.date.slice(0,7)));settings.capitalAdjustments.forEach(a=>/^\d{4}-\d{2}/.test(a.date||'')&&set.add(a.date.slice(0,7)));return [...set].sort()}
function capitalAt(m){if(!settings.capitalOpening)return null;let total=Number(settings.capitalOpening.balance||0),start=settings.capitalOpening.date||'0000-00-00';tx.filter(capitalEligible).forEach(x=>{if((x.date||'')>start&&(x.date||'').slice(0,7)<=m)total+=Number(x.amount||0)});settings.capitalAdjustments.forEach(a=>{if((a.date||'')>start&&(a.date||'').slice(0,7)<=m)total+=Number(a.amount||0)});return total}
function trend(){if(!settings.capitalOpening)return `<div class="section-title"><h2>Andamento</h2><small>capitale reale</small></div><div class="notice">Per attivare l'andamento patrimoniale serve il saldo iniziale certificato. Importa la configurazione privata oppure impostalo manualmente.</div><button class="choiceBtn" onclick="setCapitalOpening()">Imposta saldo iniziale</button>`;let months=capitalMonths(),selected=months.includes(trendMonth)?trendMonth:(months.at(-1)||monthNow()),f=capitalFlow(selected),cap=capitalAt(selected),pts=months.map(m=>({m,v:capitalAt(m)})),vals=pts.map(p=>p.v),min=Math.min(0,...vals),max=Math.max(0,...vals),range=max-min||1,w=320,h=150,pad=16,coords=pts.map((p,i)=>({x:pad+(pts.length===1?(w-2*pad)/2:i*(w-2*pad)/(pts.length-1)),y:pad+(max-p.v)*(h-2*pad)/range,...p})),poly=coords.map(p=>`${p.x},${p.y}`).join(' '),zero=pad+max*(h-2*pad)/range;return `<div class="section-title"><h2>Andamento</h2><small>entrate − uscite, senza esclusioni</small></div><div class="trendCard ${f.net<0?'loss':''}"><div class="trendHead"><div><small>VARIAZIONE DEL MESE</small><h3>${monthName(selected)}</h3></div><select id="trendMonth">${months.slice().reverse().map(m=>`<option value="${m}" ${m===selected?'selected':''}>${monthName(m)}</option>`).join('')}</select></div><div class="trendValue ${f.net>=0?'positive':'negative'}">${f.net>=0?'+':''}${money(f.net)}</div><div class="equation">${money(f.incoming)} entrate − ${money(f.outgoing)} uscite${f.adjust?` ${f.adjust>=0?'+':'−'} ${money(Math.abs(f.adjust))} rettifica E/C`:''}</div></div><div class="section-title"><h2>Andamento generale</h2><small>capitale ricostruito</small></div><div class="card patrimonial"><small>CAPITALE AL ${selected.slice(5,7)}/${selected.slice(0,4)}</small><b class="${cap>=0?'positive':'negative'}">${money(cap)}</b><div class="chart"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line x1="${pad}" y1="${zero}" x2="${w-pad}" y2="${zero}" class="zero"/><polyline points="${poly}" class="line" fill="none"/>${coords.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="3"/>`).join('')}</svg></div><div class="chartLabels"><span>${months.length?monthName(months[0]).split(' ')[0]:''}</span><span>${months.length?monthName(months.at(-1)).split(' ')[0]:''}</span></div><div class="notice compact">Base: ${money(settings.capitalOpening.balance)} al ${fmtDate(settings.capitalOpening.date)}. Nel capitale contano tutti i movimenti contabilizzati: accrediti positivi e addebiti negativi, compresi giroconti e trasferimenti.</div></div>`}
window.setCapitalOpening=()=>modalForm('Saldo iniziale capitale',`<label>Data saldo<input id="date" type="date" required value="${settings.capitalOpening?.date||'2025-12-31'}"></label><label>Saldo certificato<input id="amount" type="number" step=".01" required value="${settings.capitalOpening?.balance||0}"></label>`,d=>settings.capitalOpening={date:d.querySelector('#date').value,balance:+d.querySelector('#amount').value})
function budget(){let cats=categories(),spent={};cats.forEach(c=>spent[c]=0);variableTx(budgetMonth).forEach(x=>{let c=catOf(x);if(c)spent[c]+=Math.abs(Number(x.amount||0))});let total=cats.reduce((s,c)=>s+Number(settings.budgetLimits[c]||0),0),used=Object.values(spent).reduce((a,b)=>a+b,0),months=availableMonths().slice().reverse();return `<div class="section-title"><h2>Budget</h2><button class="textBtn" onclick="editBudget()">＋ Nuovo</button></div><div class="historyPicker"><span>Visualizza mese</span><select id="budgetMonth">${months.map(m=>`<option value="${m}" ${m===budgetMonth?'selected':''}>${monthName(m)}</option>`).join('')}</select></div><div class="budgetSummary"><div><small>BUDGET TOTALE</small><b>${money(total)}</b></div><div><small>SPESO</small><b>${money(used)}</b></div><div><small>RESTA</small><b class="${total-used>=0?'positive':'negative'}">${money(total-used)}</b></div></div>${cats.map(c=>{let l=Number(settings.budgetLimits[c]),u=spent[c]||0,d=l-u,p=l?Math.min(100,u/l*100):100;return `<button class="budgetCat editable ${d<0?'over':''}" onclick="editBudget('${encodeURIComponent(c)}')"><div class="catTop"><span>${icon(c)} ${esc(c)}</span><b>${money(u)} / ${money(l)}</b></div><div class="bar"><i style="width:${p}%"></i></div><div class="catMeta">${d>=0?'Chiusura: residuo '+money(d):'Chiusura: sforamento '+money(-d)}</div></button>`}).join('')||'<div class="emptySmall">Crea il primo budget.</div>'}<div class="notice">Puoi scegliere qualsiasi mese precedente per vedere come ha chiuso ogni budget. Lo storico viene riclassificato automaticamente nelle categorie attuali quando riconoscibile.</div>`}
function investments(){let month=allocFor('investment',monthNow()),total=settings.investedBalance+allocFor('investment');return `<div class="section-title"><h2>Investimenti</h2><button class="textBtn" onclick="setBase('investment')">Aggiorna base</button></div><div class="budgetHero"><div class="eyebrow">CAPITALE INVESTITO</div><div class="budgetHeadline">${money(total)}</div><div class="sub">Accantonato questo mese: ${money(month)}</div></div><button class="choiceBtn" onclick="addAllocation('investment')">＋ Registra investimento</button>`}
function risk(){let total=settings.riskFundBalance+allocFor('risk'),month=allocFor('risk',monthNow());return `<div class="section-title"><h2>Fondo rischi</h2><button class="textBtn" onclick="setBase('risk')">Aggiorna base</button></div><div class="budgetHero"><div class="eyebrow">FONDO DISPONIBILE</div><div class="budgetHeadline">${money(total)}</div><div class="sub">Accantonato questo mese: ${money(month)}</div></div><button class="choiceBtn" onclick="addAllocation('risk')">＋ Accantona nel fondo</button>`}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#view').innerHTML=({fixed,movements,trend,budget,investments,risk}[view]||fixed)();let tm=$('#trendMonth');if(tm)tm.onchange=()=>{trendMonth=tm.value;render()};let mm=$('#movementMonth');if(mm)mm.onchange=()=>{movementMonth=mm.value;render()};let mc=$('#movementCat');if(mc)mc.onchange=()=>{movementCat=mc.value;render()};let bm=$('#budgetMonth');if(bm)bm.onchange=()=>{budgetMonth=bm.value;render()}}
function modalForm(title,body,onSave,onDelete){let d=$('#modal');d.innerHTML=`<form id="modalForm"><h2>${title}</h2>${body}<div class="actions">${onDelete?'<button type="button" class="btn dangerBtn" id="deleteBtn">Elimina</button>':''}<button type="button" class="btn secondary" id="cancelBtn">Annulla</button><button class="btn primary">Salva</button></div></form>`;d.showModal();$('#cancelBtn').onclick=()=>d.close();if(onDelete)$('#deleteBtn').onclick=()=>{onDelete();d.close();save();render()};$('#modalForm').onsubmit=e=>{e.preventDefault();onSave(d);d.close();save();render()}}
window.editIncome=id=>{let row=id?settings.fixedIncome.find(x=>x.id===id):null,r=row||{id:uid(),name:'',amount:0,day:1,enabled:true,startMonth:monthNow()};modalForm(row?'Modifica entrata fissa':'Nuova entrata fissa',`<label>Nome<input id="name" required value="${esc(r.name)}"></label><label>Importo mensile<input id="amount" type="number" min="0" step=".01" required value="${r.amount||0}"></label><label>Giorno previsto<input id="day" type="number" min="1" max="31" required value="${r.day||1}"></label><label>Attiva dal mese<input id="start" type="month" value="${r.startMonth||monthNow()}"></label>`,d=>{r.name=d.querySelector('#name').value.trim();r.amount=+d.querySelector('#amount').value;r.day=+d.querySelector('#day').value;r.startMonth=d.querySelector('#start').value||monthNow();r.enabled=true;if(!row)settings.fixedIncome.push(r)},row?()=>settings.fixedIncome=settings.fixedIncome.filter(x=>x.id!==r.id):null)}
window.editFixed=id=>{let row=id?settings.fixedExpenses.find(x=>x.id===id):null,r=row||{id:uid(),name:'',amount:0,day:1,enabled:true,startMonth:monthNow()};modalForm(row?'Modifica spesa fissa':'Nuova spesa fissa',`<label>Nome<input id="name" required value="${esc(r.name)}"></label><label>Importo mensile<input id="amount" type="number" min="0" step=".01" required value="${r.amount||0}"></label><label>Giorno previsto<input id="day" type="number" min="1" max="31" required value="${r.day||1}"></label><label>Attiva dal mese<input id="start" type="month" value="${r.startMonth||monthNow()}"></label>`,d=>{r.name=d.querySelector('#name').value.trim();r.amount=+d.querySelector('#amount').value;r.day=+d.querySelector('#day').value;r.startMonth=d.querySelector('#start').value||monthNow();r.enabled=true;if(!row)settings.fixedExpenses.push(r)},row?()=>settings.fixedExpenses=settings.fixedExpenses.filter(x=>x.id!==r.id):null)}
window.editBudget=encoded=>{let oldName=encoded?decodeURIComponent(encoded):'',exists=Object.hasOwn(settings.budgetLimits,oldName);modalForm(exists?'Modifica budget':'Nuovo budget',`<label>Nome / categoria<input id="name" required value="${esc(oldName)}"></label><label>Budget mensile<input id="amount" type="number" min="0" step=".01" required value="${exists?settings.budgetLimits[oldName]:0}"></label>`,d=>{let n=d.querySelector('#name').value.trim(),a=+d.querySelector('#amount').value;if(oldName&&oldName!==n){delete settings.budgetLimits[oldName];tx.forEach(x=>{if(x.budgetCategory===oldName)x.budgetCategory=n;if(x.category===oldName)x.category=n})}settings.budgetLimits[n]=a},exists?()=>delete settings.budgetLimits[oldName]:null)}
function addExpense(){let cats=categories();if(!cats.length){alert('Crea prima almeno un Budget: sarà anche la categoria della spesa.');view='budget';render();return}modalForm('Nuova spesa',`<label>Data<input id="date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Descrizione<input id="desc" required placeholder="Es. Caffè"></label><label>Categoria<select id="cat">${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><label>Importo<input id="amount" type="number" min="0.01" step=".01" required></label>`,d=>{let c=d.querySelector('#cat').value;tx.push({id:uid(),date:d.querySelector('#date').value,description:d.querySelector('#desc').value.trim(),category:c,budgetCategory:c,amount:-Math.abs(+d.querySelector('#amount').value),currency:'EUR',flowType:'variable_expense',createdBy:'saldo-v062'})})}
window.addAllocation=dest=>modalForm(dest==='risk'?'Accantona nel Fondo rischi':'Registra investimento',`<label>Data<input id="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Importo<input id="amount" type="number" min="0.01" step=".01" required></label>`,d=>settings.allocations.push({id:uid(),date:d.querySelector('#date').value,amount:+d.querySelector('#amount').value,destination:dest}))
window.setBase=dest=>{let key=dest==='risk'?'riskFundBalance':'investedBalance';modalForm('Aggiorna capitale iniziale',`<label>Importo già presente<input id="amount" type="number" min="0" step=".01" value="${settings[key]||0}"></label>`,d=>settings[key]=+d.querySelector('#amount').value)}
function icon(c){let s=String(c||'').toLowerCase();if(s.includes('bar'))return'☕';if(s.includes('aliment'))return'🛒';if(s.includes('tabac'))return'◉';if(s.includes('salute'))return'✚';if(s.includes('shopping'))return'▣';return'•'} function fmtDate(d){if(!d)return'';let [y,m,day]=d.split('-');return `${day}/${m}/${y}`}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('#fab').onclick=addExpense;
$('#backupBtn').onclick=()=>{let blob=new Blob([JSON.stringify({version:APP_VERSION,exportedAt:new Date().toISOString(),transactions:tx,settings},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`SALDO_backup_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importBtn').onclick=()=>{let i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{let d=JSON.parse(await i.files[0].text());if(d.settingsPatch&&typeof d.settingsPatch==='object'){settings={...settings,...d.settingsPatch};save();render();alert('Configurazione privata aggiornata. I movimenti esistenti non sono stati modificati.');return}if(!Array.isArray(d.transactions))throw Error();tx=d.transactions;if(d.settings)settings={...settings,...d.settings,fixedIncome:d.settings.fixedIncome||settings.fixedIncome,fixedExpenses:d.settings.fixedExpenses||settings.fixedExpenses,budgetLimits:d.settings.budgetLimits||settings.budgetLimits,allocations:d.settings.allocations||settings.allocations};save();render();alert('Importazione completata.')}catch{alert('File di backup non valido.')}};i.click()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=062').then(r=>r.update()).catch(()=>{});save();render();
